name: task_management
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.13
  flutter_bloc: ^8.1.6
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  hive: ^2.2.3
  build_runner: ^2.4.13
  flutter_slidable: ^3.1.1
  sqflite: ^2.4.1
  intl: ^0.20.0
  shared_preferences: ^2.3.3



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/icons/



